# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 01:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sisprocon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresas',
            name='idEmpresa',
        ),
        migrations.RemoveField(
            model_name='fiscalizacoes',
            name='idFisc',
        ),
        migrations.RemoveField(
            model_name='orgaosfiscalizadores',
            name='idOrgao',
        ),
        migrations.RemoveField(
            model_name='pesquisas',
            name='idPesquisa',
        ),
        migrations.RemoveField(
            model_name='precos',
            name='idEmpresa',
        ),
        migrations.RemoveField(
            model_name='precos',
            name='idPesquisa',
        ),
        migrations.RemoveField(
            model_name='precos',
            name='idProduto',
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='idProduto',
        ),
        migrations.AddField(
            model_name='precos',
            name='idProdutoEmpresa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sisprocon.ProdutosDasEmpresas'),
        ),
    ]
