# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 02:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sisprocon', '0002_auto_20171119_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresas',
            old_name='nome',
            new_name='razaoSocial',
        ),
        migrations.AddField(
            model_name='precos',
            name='idPesquisa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sisprocon.Pesquisas'),
        ),
    ]
